# Generated by Django 4.2.1 on 2023-05-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0003_alter_mytask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytask',
            name='desc',
            field=models.CharField(max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='task_title',
            field=models.CharField(max_length=50, verbose_name='task_title'),
        ),
    ]
