# Generated by Django 4.2.1 on 2023-05-10 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0004_alter_mytask_desc_alter_mytask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
