# Generated by Django 4.2.1 on 2023-05-10 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mytask', '0005_mytask_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='date',
            new_name='edate',
        ),
        migrations.AddField(
            model_name='mytask',
            name='sdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
